/*
 * Anserini: A Lucene toolkit for reproducible information retrieval research
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.anserini.doc;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.dataformat.yaml.YAMLFactory;
import org.apache.commons.io.FileUtils;
import org.apache.commons.text.StringSubstitutor;
import org.junit.Test;

import static org.junit.Assert.assertNotNull;

import java.io.File;
import java.net.URL;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.Set;
import java.util.Scanner;
import java.util.regex.Pattern;

public class GenerateReproductionDocsFromDocumentCollectionTest {
  private static final Map<String, List<String>> ORDERING = new LinkedHashMap<>();

  static {
    ORDERING.put("CACM tests", List.of(
        Pattern.quote("cacm"),
        Pattern.quote("cacm-download")
    ));
    ORDERING.put("MS MARCO V1 + DL19/DL20 regressions", List.of(
        Pattern.quote("msmarco-v1-passage"),
        Pattern.quote("msmarco-v1-passage.bm25-b8"),
        Pattern.quote("msmarco-v1-passage.wp-tok"),
        Pattern.quote("msmarco-v1-passage.wp-hgf"),
        Pattern.quote("msmarco-v1-passage.wp-ca"),
        Pattern.quote("msmarco-v1-passage.doc2query"),
        Pattern.quote("msmarco-v1-passage.docTTTTTquery"),
        Pattern.quote(""),
        Pattern.quote("msmarco-v1-passage.deepimpact.cached"),
        Pattern.quote("msmarco-v1-passage.unicoil.cached"),
        Pattern.quote("msmarco-v1-passage.unicoil-noexp.cached"),
        Pattern.quote("msmarco-v1-passage.unicoil-tilde-expansion.cached"),
        Pattern.quote("msmarco-v1-passage.distill-splade-max.cached"),
        Pattern.quote("msmarco-v1-passage.splade-pp-ed.cached"),
        Pattern.quote("msmarco-v1-passage.splade-pp-ed.onnx"),
        Pattern.quote("msmarco-v1-passage.splade-pp-sd.cached"),
        Pattern.quote("msmarco-v1-passage.splade-pp-sd.onnx"),
        Pattern.quote("msmarco-v1-passage.splade-v3.onnx"),
        Pattern.quote("msmarco-v1-passage.splade-v3.cached"),
        Pattern.quote(""),
        Pattern.quote("msmarco-v1-passage.cos-dpr-distil.parquet.fw"),
        Pattern.quote("msmarco-v1-passage.cos-dpr-distil.parquet.lexlsh"),
        Pattern.quote("msmarco-v1-passage.cos-dpr-distil.parquet.flat.cached"),
        Pattern.quote("msmarco-v1-passage.cos-dpr-distil.parquet.flat.onnx"),
        Pattern.quote("msmarco-v1-passage.cos-dpr-distil.parquet.flat-int8.cached"),
        Pattern.quote("msmarco-v1-passage.cos-dpr-distil.parquet.flat-int8.onnx"),
        Pattern.quote("msmarco-v1-passage.cos-dpr-distil.parquet.hnsw.cached"),
        Pattern.quote("msmarco-v1-passage.cos-dpr-distil.parquet.hnsw.onnx"),
        Pattern.quote("msmarco-v1-passage.cos-dpr-distil.parquet.hnsw-int8.cached"),
        Pattern.quote("msmarco-v1-passage.cos-dpr-distil.parquet.hnsw-int8.onnx"),
        Pattern.quote("msmarco-v1-passage.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("msmarco-v1-passage.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("msmarco-v1-passage.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("msmarco-v1-passage.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("msmarco-v1-passage.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("msmarco-v1-passage.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("msmarco-v1-passage.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("msmarco-v1-passage.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("msmarco-v1-passage.openai-ada2.parquet.flat.cached"),
        Pattern.quote("msmarco-v1-passage.openai-ada2.parquet.flat-int8.cached"),
        Pattern.quote("msmarco-v1-passage.openai-ada2.parquet.hnsw.cached"),
        Pattern.quote("msmarco-v1-passage.openai-ada2.parquet.hnsw-int8.cached"),
        Pattern.quote("msmarco-v1-passage.cohere-embed-english-v3.0.parquet.flat.cached"),
        Pattern.quote("msmarco-v1-passage.cohere-embed-english-v3.0.parquet.flat-int8.cached"),
        Pattern.quote("msmarco-v1-passage.cohere-embed-english-v3.0.parquet.hnsw.cached"),
        Pattern.quote("msmarco-v1-passage.cohere-embed-english-v3.0.parquet.hnsw-int8.cached"),
        Pattern.quote(""),
        Pattern.quote("msmarco-v1-doc"),
        Pattern.quote("msmarco-v1-doc.wp-tok"),
        Pattern.quote("msmarco-v1-doc.wp-hgf"),
        Pattern.quote("msmarco-v1-doc.wp-ca"),
        Pattern.quote("msmarco-v1-doc.docTTTTTquery"),
        Pattern.quote(""),
        Pattern.quote("msmarco-v1-doc-segmented"),
        Pattern.quote("msmarco-v1-doc-segmented.wp-tok"),
        Pattern.quote("msmarco-v1-doc-segmented.wp-ca"),
        Pattern.quote("msmarco-v1-doc-segmented.docTTTTTquery"),
        Pattern.quote("msmarco-v1-doc-segmented.unicoil.cached"),
        Pattern.quote("msmarco-v1-doc-segmented.unicoil-noexp.cached"),
        Pattern.quote(""),
        Pattern.quote("dl19-passage"),
        Pattern.quote("dl19-passage.bm25-b8"),
        Pattern.quote("dl19-passage.wp-tok"),
        Pattern.quote("dl19-passage.wp-hgf"),
        Pattern.quote("dl19-passage.wp-ca"),
        Pattern.quote("dl19-passage.docTTTTTquery"),
        Pattern.quote(""),
        Pattern.quote("dl19-passage.unicoil.cached"),
        Pattern.quote("dl19-passage.unicoil-noexp.cached"),
        Pattern.quote("dl19-passage.splade-pp-ed.cached"),
        Pattern.quote("dl19-passage.splade-pp-ed.onnx"),
        Pattern.quote("dl19-passage.splade-pp-sd.cached"),
        Pattern.quote("dl19-passage.splade-pp-sd.onnx"),
        Pattern.quote("dl19-passage.splade-v3.onnx"),
        Pattern.quote("dl19-passage.splade-v3.cached"),
        Pattern.quote(""),
        Pattern.quote("dl19-passage.cos-dpr-distil.parquet.fw"),
        Pattern.quote("dl19-passage.cos-dpr-distil.parquet.lexlsh"),
        Pattern.quote("dl19-passage.cos-dpr-distil.parquet.flat.cached"),
        Pattern.quote("dl19-passage.cos-dpr-distil.parquet.flat.onnx"),
        Pattern.quote("dl19-passage.cos-dpr-distil.parquet.flat-int8.cached"),
        Pattern.quote("dl19-passage.cos-dpr-distil.parquet.flat-int8.onnx"),
        Pattern.quote("dl19-passage.cos-dpr-distil.parquet.hnsw.cached"),
        Pattern.quote("dl19-passage.cos-dpr-distil.parquet.hnsw.onnx"),
        Pattern.quote("dl19-passage.cos-dpr-distil.parquet.hnsw-int8.cached"),
        Pattern.quote("dl19-passage.cos-dpr-distil.parquet.hnsw-int8.onnx"),
        Pattern.quote("dl19-passage.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("dl19-passage.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("dl19-passage.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("dl19-passage.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("dl19-passage.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("dl19-passage.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("dl19-passage.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("dl19-passage.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("dl19-passage.openai-ada2.parquet.flat.cached"),
        Pattern.quote("dl19-passage.openai-ada2.parquet.flat-int8.cached"),
        Pattern.quote("dl19-passage.openai-ada2.parquet.hnsw.cached"),
        Pattern.quote("dl19-passage.openai-ada2.parquet.hnsw-int8.cached"),
        Pattern.quote("dl19-passage.cohere-embed-english-v3.0.parquet.flat.cached"),
        Pattern.quote("dl19-passage.cohere-embed-english-v3.0.parquet.flat-int8.cached"),
        Pattern.quote("dl19-passage.cohere-embed-english-v3.0.parquet.hnsw.cached"),
        Pattern.quote("dl19-passage.cohere-embed-english-v3.0.parquet.hnsw-int8.cached"),
        Pattern.quote(""),
        Pattern.quote("dl19-doc"),
        Pattern.quote("dl19-doc.wp-tok"),
        Pattern.quote("dl19-doc.wp-hgf"),
        Pattern.quote("dl19-doc.wp-ca"),
        Pattern.quote("dl19-doc.docTTTTTquery"),
        Pattern.quote(""),
        Pattern.quote("dl19-doc-segmented"),
        Pattern.quote("dl19-doc-segmented.wp-tok"),
        Pattern.quote("dl19-doc-segmented.wp-ca"),
        Pattern.quote("dl19-doc-segmented.docTTTTTquery"),
        Pattern.quote("dl19-doc-segmented.unicoil.cached"),
        Pattern.quote("dl19-doc-segmented.unicoil-noexp.cached"),
        Pattern.quote(""),
        Pattern.quote("dl20-passage"),
        Pattern.quote("dl20-passage.bm25-b8"),
        Pattern.quote("dl20-passage.wp-tok"),
        Pattern.quote("dl20-passage.wp-hgf"),
        Pattern.quote("dl20-passage.wp-ca"),
        Pattern.quote("dl20-passage.docTTTTTquery"),
        Pattern.quote(""),
        Pattern.quote("dl20-passage.unicoil.cached"),
        Pattern.quote("dl20-passage.unicoil-noexp.cached"),
        Pattern.quote("dl20-passage.splade-pp-ed.cached"),
        Pattern.quote("dl20-passage.splade-pp-ed.onnx"),
        Pattern.quote("dl20-passage.splade-pp-sd.cached"),
        Pattern.quote("dl20-passage.splade-pp-sd.onnx"),
        Pattern.quote("dl20-passage.splade-v3.onnx"),
        Pattern.quote("dl20-passage.splade-v3.cached"),
        Pattern.quote(""),
        Pattern.quote("dl20-passage.cos-dpr-distil.parquet.fw"),
        Pattern.quote("dl20-passage.cos-dpr-distil.parquet.lexlsh"),
        Pattern.quote("dl20-passage.cos-dpr-distil.parquet.flat.cached"),
        Pattern.quote("dl20-passage.cos-dpr-distil.parquet.flat.onnx"),
        Pattern.quote("dl20-passage.cos-dpr-distil.parquet.flat-int8.cached"),
        Pattern.quote("dl20-passage.cos-dpr-distil.parquet.flat-int8.onnx"),
        Pattern.quote("dl20-passage.cos-dpr-distil.parquet.hnsw.cached"),
        Pattern.quote("dl20-passage.cos-dpr-distil.parquet.hnsw.onnx"),
        Pattern.quote("dl20-passage.cos-dpr-distil.parquet.hnsw-int8.cached"),
        Pattern.quote("dl20-passage.cos-dpr-distil.parquet.hnsw-int8.onnx"),
        Pattern.quote("dl20-passage.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("dl20-passage.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("dl20-passage.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("dl20-passage.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("dl20-passage.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("dl20-passage.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("dl20-passage.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("dl20-passage.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("dl20-passage.openai-ada2.parquet.flat.cached"),
        Pattern.quote("dl20-passage.openai-ada2.parquet.flat-int8.cached"),
        Pattern.quote("dl20-passage.openai-ada2.parquet.hnsw.cached"),
        Pattern.quote("dl20-passage.openai-ada2.parquet.hnsw-int8.cached"),
        Pattern.quote("dl20-passage.cohere-embed-english-v3.0.parquet.flat.cached"),
        Pattern.quote("dl20-passage.cohere-embed-english-v3.0.parquet.flat-int8.cached"),
        Pattern.quote("dl20-passage.cohere-embed-english-v3.0.parquet.hnsw.cached"),
        Pattern.quote("dl20-passage.cohere-embed-english-v3.0.parquet.hnsw-int8.cached"),
        Pattern.quote(""),
        Pattern.quote("dl20-doc"),
        Pattern.quote("dl20-doc.wp-tok"),
        Pattern.quote("dl20-doc.wp-hgf"),
        Pattern.quote("dl20-doc.wp-ca"),
        Pattern.quote("dl20-doc.docTTTTTquery"),
        Pattern.quote(""),
        Pattern.quote("dl20-doc-segmented"),
        Pattern.quote("dl20-doc-segmented.wp-tok"),
        Pattern.quote("dl20-doc-segmented.wp-ca"),
        Pattern.quote("dl20-doc-segmented.docTTTTTquery"),
        Pattern.quote("dl20-doc-segmented.unicoil.cached"),
        Pattern.quote("dl20-doc-segmented.unicoil-noexp.cached")
    ));
    ORDERING.put("MS MARCO V2 + DL21 regressions", List.of(
        Pattern.quote("msmarco-v2-passage"),
        Pattern.quote("msmarco-v2-passage.d2q-t5"),
        Pattern.quote("msmarco-v2-passage.unicoil-noexp-0shot.cached"),
        Pattern.quote("msmarco-v2-passage.unicoil-0shot.cached"),
        Pattern.quote("msmarco-v2-passage.splade-pp-ed.cached"),
        Pattern.quote("msmarco-v2-passage.splade-pp-ed.onnx"),
        Pattern.quote("msmarco-v2-passage.splade-pp-sd.cached"),
        Pattern.quote("msmarco-v2-passage.splade-pp-sd.onnx"),
        Pattern.quote("msmarco-v2-passage-augmented"),
        Pattern.quote("msmarco-v2-passage-augmented.d2q-t5"),
        Pattern.quote("msmarco-v2-doc"),
        Pattern.quote("msmarco-v2-doc.d2q-t5"),
        Pattern.quote("msmarco-v2-doc-segmented"),
        Pattern.quote("msmarco-v2-doc-segmented.d2q-t5"),
        Pattern.quote("msmarco-v2-doc-segmented.unicoil-noexp-0shot-v2.cached"),
        Pattern.quote("msmarco-v2-doc-segmented.unicoil-0shot-v2.cached"),
        Pattern.quote("dl21-passage"),
        Pattern.quote("dl21-passage.d2q-t5"),
        Pattern.quote("dl21-passage.unicoil-noexp-0shot.cached"),
        Pattern.quote("dl21-passage.unicoil-0shot.cached"),
        Pattern.quote("dl21-passage.splade-pp-ed.cached"),
        Pattern.quote("dl21-passage.splade-pp-ed.onnx"),
        Pattern.quote("dl21-passage.splade-pp-sd.cached"),
        Pattern.quote("dl21-passage.splade-pp-sd.onnx"),
        Pattern.quote("dl21-passage-augmented"),
        Pattern.quote("dl21-passage-augmented.d2q-t5"),
        Pattern.quote("dl21-doc"),
        Pattern.quote("dl21-doc.d2q-t5"),
        Pattern.quote("dl21-doc-segmented"),
        Pattern.quote("dl21-doc-segmented.d2q-t5"),
        Pattern.quote("dl21-doc-segmented.unicoil-noexp-0shot-v2.cached"),
        Pattern.quote("dl21-doc-segmented.unicoil-0shot-v2.cached"),
        Pattern.quote("dl22-passage"),
        Pattern.quote("dl22-passage.d2q-t5"),
        Pattern.quote("dl22-passage.unicoil-noexp-0shot.cached"),
        Pattern.quote("dl22-passage.unicoil-0shot.cached"),
        Pattern.quote("dl22-passage.splade-pp-ed.cached"),
        Pattern.quote("dl22-passage.splade-pp-ed.onnx"),
        Pattern.quote("dl22-passage.splade-pp-sd.cached"),
        Pattern.quote("dl22-passage.splade-pp-sd.onnx"),
        Pattern.quote("dl22-passage-augmented"),
        Pattern.quote("dl22-passage-augmented.d2q-t5"),
        Pattern.quote("dl22-doc"),
        Pattern.quote("dl22-doc.d2q-t5"),
        Pattern.quote("dl22-doc-segmented"),
        Pattern.quote("dl22-doc-segmented.d2q-t5"),
        Pattern.quote("dl22-doc-segmented.unicoil-noexp-0shot-v2.cached"),
        Pattern.quote("dl22-doc-segmented.unicoil-0shot-v2.cached"),
        Pattern.quote("dl23-passage"),
        Pattern.quote("dl23-passage.d2q-t5"),
        Pattern.quote("dl23-passage.unicoil-noexp-0shot.cached"),
        Pattern.quote("dl23-passage.unicoil-0shot.cached"),
        Pattern.quote("dl23-passage.splade-pp-ed.cached"),
        Pattern.quote("dl23-passage.splade-pp-ed.onnx"),
        Pattern.quote("dl23-passage.splade-pp-sd.cached"),
        Pattern.quote("dl23-passage.splade-pp-sd.onnx"),
        Pattern.quote("dl23-passage-augmented"),
        Pattern.quote("dl23-passage-augmented.d2q-t5"),
        Pattern.quote("dl23-doc"),
        Pattern.quote("dl23-doc.d2q-t5"),
        Pattern.quote("dl23-doc-segmented"),
        Pattern.quote("dl23-doc-segmented.d2q-t5"),
        Pattern.quote("dl23-doc-segmented.unicoil-noexp-0shot-v2.cached"),
        Pattern.quote("dl23-doc-segmented.unicoil-0shot-v2.cached")
    ));
    ORDERING.put("MS MARCO V2.1 + RAG24 regressions", List.of(
        Pattern.quote("rag24-doc-segmented-test-umbrela"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.splade-v3.onnx"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.splade-v3.cached"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.arctic-embed-l.parquet.shard00.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.arctic-embed-l.parquet.shard01.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.arctic-embed-l.parquet.shard02.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.arctic-embed-l.parquet.shard03.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.arctic-embed-l.parquet.shard04.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.arctic-embed-l.parquet.shard05.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.arctic-embed-l.parquet.shard06.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.arctic-embed-l.parquet.shard07.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.arctic-embed-l.parquet.shard08.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-umbrela.arctic-embed-l.parquet.shard09.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-nist"),
        Pattern.quote("rag24-doc-segmented-test-nist.splade-v3.onnx"),
        Pattern.quote("rag24-doc-segmented-test-nist.splade-v3.cached"),
        Pattern.quote("rag24-doc-segmented-test-nist.arctic-embed-l.parquet.shard00.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-nist.arctic-embed-l.parquet.shard01.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-nist.arctic-embed-l.parquet.shard02.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-nist.arctic-embed-l.parquet.shard03.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-nist.arctic-embed-l.parquet.shard04.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-nist.arctic-embed-l.parquet.shard05.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-nist.arctic-embed-l.parquet.shard06.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-nist.arctic-embed-l.parquet.shard07.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-nist.arctic-embed-l.parquet.shard08.flat.onnx"),
        Pattern.quote("rag24-doc-segmented-test-nist.arctic-embed-l.parquet.shard09.flat.onnx"),
        Pattern.quote("msmarco-v2.1-doc"),
        Pattern.quote("msmarco-v2.1-doc-segmented"),
        Pattern.quote("msmarco-v2.1-doc-segmented.splade-v3.onnx"),
        Pattern.quote("msmarco-v2.1-doc-segmented.splade-v3.cached"),
        Pattern.quote("dl21-doc-msmarco-v2.1"),
        Pattern.quote("dl21-doc-segmented-msmarco-v2.1"),
        Pattern.quote("dl21-doc-segmented-msmarco-v2.1.splade-v3.onnx"),
        Pattern.quote("dl21-doc-segmented-msmarco-v2.1.splade-v3.cached"),
        Pattern.quote("dl22-doc-msmarco-v2.1"),
        Pattern.quote("dl22-doc-segmented-msmarco-v2.1"),
        Pattern.quote("dl22-doc-segmented-msmarco-v2.1.splade-v3.onnx"),
        Pattern.quote("dl22-doc-segmented-msmarco-v2.1.splade-v3.cached"),
        Pattern.quote("dl23-doc-msmarco-v2.1"),
        Pattern.quote("dl23-doc-segmented-msmarco-v2.1"),
        Pattern.quote("dl23-doc-segmented-msmarco-v2.1.splade-v3.onnx"),
        Pattern.quote("dl23-doc-segmented-msmarco-v2.1.splade-v3.cached"),
        Pattern.quote("rag24-doc-raggy-dev"),
        Pattern.quote("rag24-doc-segmented-raggy-dev"),
        Pattern.quote("rag24-doc-segmented-raggy-dev.splade-v3.onnx"),
        Pattern.quote("rag24-doc-segmented-raggy-dev.splade-v3.cached"),
        Pattern.quote("rag25-doc-segmented-test-nist"),
        Pattern.quote("rag25-doc-segmented-test-umbrela2")
    ));
    ORDERING.put("BEIR (v1.0.0): BGE-base-en-v1.5", List.of(
        Pattern.quote("beir-v1.0.0-arguana.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-bioasq.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-climate-fever.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-fever.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-fiqa.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-hotpotqa.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-nfcorpus.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-nq.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-quora.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-robust04.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-scidocs.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-scifact.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-signal1m.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-trec-covid.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-trec-news.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.bge-base-en-v1.5.parquet.flat.cached"),
        Pattern.quote("beir-v1.0.0-arguana.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-bioasq.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-climate-fever.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-fever.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-fiqa.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-hotpotqa.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-nfcorpus.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-nq.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-quora.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-robust04.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-scidocs.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-scifact.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-signal1m.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-trec-covid.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-trec-news.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.bge-base-en-v1.5.parquet.flat.onnx"),
        Pattern.quote("beir-v1.0.0-arguana.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-bioasq.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-climate-fever.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-fever.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-fiqa.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-hotpotqa.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-nfcorpus.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-nq.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-quora.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-robust04.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-scidocs.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-scifact.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-signal1m.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-trec-covid.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-trec-news.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.bge-base-en-v1.5.parquet.flat-int8.cached"),
        Pattern.quote("beir-v1.0.0-arguana.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-bioasq.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-climate-fever.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-fever.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-fiqa.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-hotpotqa.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-nfcorpus.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-nq.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-quora.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-robust04.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-scidocs.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-scifact.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-signal1m.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-trec-covid.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-trec-news.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.bge-base-en-v1.5.parquet.flat-int8.onnx"),
        Pattern.quote("beir-v1.0.0-trec-covid.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-bioasq.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-nfcorpus.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-nq.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-hotpotqa.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-fiqa.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-signal1m.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-trec-news.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-robust04.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-arguana.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-quora.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-scidocs.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-fever.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-climate-fever.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-scifact.bge-base-en-v1.5.parquet.hnsw.cached"),
        Pattern.quote("beir-v1.0.0-trec-covid.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-bioasq.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-nfcorpus.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-nq.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-hotpotqa.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-fiqa.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-signal1m.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-trec-news.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-robust04.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-arguana.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-quora.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-scidocs.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-fever.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-climate-fever.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-scifact.bge-base-en-v1.5.parquet.hnsw.onnx"),
        Pattern.quote("beir-v1.0.0-trec-covid.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-bioasq.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-nfcorpus.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-nq.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-hotpotqa.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-fiqa.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-signal1m.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-trec-news.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-robust04.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-arguana.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-quora.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-scidocs.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-fever.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-climate-fever.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-scifact.bge-base-en-v1.5.parquet.hnsw-int8.cached"),
        Pattern.quote("beir-v1.0.0-trec-covid.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-bioasq.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-nfcorpus.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-nq.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-hotpotqa.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-fiqa.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-signal1m.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-trec-news.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-robust04.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-arguana.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-quora.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-scidocs.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-fever.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-climate-fever.bge-base-en-v1.5.parquet.hnsw-int8.onnx"),
        Pattern.quote("beir-v1.0.0-scifact.bge-base-en-v1.5.parquet.hnsw-int8.onnx")
    ));
    ORDERING.put("BEIR (v1.0.0): SPLADE-v3", List.of(
        Pattern.quote("beir-v1.0.0-trec-covid.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-bioasq.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-nfcorpus.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-nq.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-hotpotqa.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-fiqa.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-signal1m.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-trec-news.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-robust04.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-arguana.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-quora.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-scidocs.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-fever.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-climate-fever.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-scifact.splade-v3.cached"),
        Pattern.quote("beir-v1.0.0-trec-covid.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-bioasq.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-nfcorpus.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-nq.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-hotpotqa.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-fiqa.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-signal1m.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-trec-news.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-robust04.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-arguana.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-quora.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-scidocs.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-fever.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-climate-fever.splade-v3.onnx"),
        Pattern.quote("beir-v1.0.0-scifact.splade-v3.onnx")
    ));
    ORDERING.put("BEIR (v1.0.0): SPLADE++ CoCondenser-EnsembleDistil", List.of(
        Pattern.quote("beir-v1.0.0-trec-covid.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-bioasq.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-nfcorpus.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-nq.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-hotpotqa.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-fiqa.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-signal1m.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-trec-news.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-robust04.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-arguana.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-quora.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-scidocs.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-fever.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-climate-fever.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-scifact.splade-pp-ed.cached"),
        Pattern.quote("beir-v1.0.0-trec-covid.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-bioasq.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-nfcorpus.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-nq.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-hotpotqa.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-fiqa.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-signal1m.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-trec-news.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-robust04.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-arguana.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-quora.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-scidocs.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-fever.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-climate-fever.splade-pp-ed.onnx"),
        Pattern.quote("beir-v1.0.0-scifact.splade-pp-ed.onnx")
    ));
    ORDERING.put("BEIR (v1.0.0): uniCOIL (noexp)", List.of(
        Pattern.quote("beir-v1.0.0-trec-covid.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-bioasq.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-nfcorpus.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-nq.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-hotpotqa.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-fiqa.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-signal1m.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-trec-news.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-robust04.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-arguana.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-quora.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-scidocs.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-fever.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-climate-fever.unicoil-noexp.cached"),
        Pattern.quote("beir-v1.0.0-scifact.unicoil-noexp.cached")
    ));
    ORDERING.put("BEIR (v1.0.0): \"flat\" baseline", List.of(
        Pattern.quote("beir-v1.0.0-trec-covid.flat"),
        Pattern.quote("beir-v1.0.0-bioasq.flat"),
        Pattern.quote("beir-v1.0.0-nfcorpus.flat"),
        Pattern.quote("beir-v1.0.0-nq.flat"),
        Pattern.quote("beir-v1.0.0-hotpotqa.flat"),
        Pattern.quote("beir-v1.0.0-fiqa.flat"),
        Pattern.quote("beir-v1.0.0-signal1m.flat"),
        Pattern.quote("beir-v1.0.0-trec-news.flat"),
        Pattern.quote("beir-v1.0.0-robust04.flat"),
        Pattern.quote("beir-v1.0.0-arguana.flat"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.flat"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.flat"),
        Pattern.quote("beir-v1.0.0-quora.flat"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.flat"),
        Pattern.quote("beir-v1.0.0-scidocs.flat"),
        Pattern.quote("beir-v1.0.0-fever.flat"),
        Pattern.quote("beir-v1.0.0-climate-fever.flat"),
        Pattern.quote("beir-v1.0.0-scifact.flat")
    ));
    ORDERING.put("BEIR (v1.0.0): \"flat\" baseline with WordPiece tokenization", List.of(
        Pattern.quote("beir-v1.0.0-trec-covid.flat-wp"),
        Pattern.quote("beir-v1.0.0-bioasq.flat-wp"),
        Pattern.quote("beir-v1.0.0-nfcorpus.flat-wp"),
        Pattern.quote("beir-v1.0.0-nq.flat-wp"),
        Pattern.quote("beir-v1.0.0-hotpotqa.flat-wp"),
        Pattern.quote("beir-v1.0.0-fiqa.flat-wp"),
        Pattern.quote("beir-v1.0.0-signal1m.flat-wp"),
        Pattern.quote("beir-v1.0.0-trec-news.flat-wp"),
        Pattern.quote("beir-v1.0.0-robust04.flat-wp"),
        Pattern.quote("beir-v1.0.0-arguana.flat-wp"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.flat-wp"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.flat-wp"),
        Pattern.quote("beir-v1.0.0-quora.flat-wp"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.flat-wp"),
        Pattern.quote("beir-v1.0.0-scidocs.flat-wp"),
        Pattern.quote("beir-v1.0.0-fever.flat-wp"),
        Pattern.quote("beir-v1.0.0-climate-fever.flat-wp"),
        Pattern.quote("beir-v1.0.0-scifact.flat-wp")
    ));
    ORDERING.put("BEIR (v1.0.0): \"multifield\" baseline", List.of(
        Pattern.quote("beir-v1.0.0-trec-covid.multifield"),
        Pattern.quote("beir-v1.0.0-bioasq.multifield"),
        Pattern.quote("beir-v1.0.0-nfcorpus.multifield"),
        Pattern.quote("beir-v1.0.0-nq.multifield"),
        Pattern.quote("beir-v1.0.0-hotpotqa.multifield"),
        Pattern.quote("beir-v1.0.0-fiqa.multifield"),
        Pattern.quote("beir-v1.0.0-signal1m.multifield"),
        Pattern.quote("beir-v1.0.0-trec-news.multifield"),
        Pattern.quote("beir-v1.0.0-robust04.multifield"),
        Pattern.quote("beir-v1.0.0-arguana.multifield"),
        Pattern.quote("beir-v1.0.0-webis-touche2020.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-android.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-english.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gaming.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-gis.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-mathematica.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-physics.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-programmers.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-stats.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-tex.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-unix.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-webmasters.multifield"),
        Pattern.quote("beir-v1.0.0-cqadupstack-wordpress.multifield"),
        Pattern.quote("beir-v1.0.0-quora.multifield"),
        Pattern.quote("beir-v1.0.0-dbpedia-entity.multifield"),
        Pattern.quote("beir-v1.0.0-scidocs.multifield"),
        Pattern.quote("beir-v1.0.0-fever.multifield"),
        Pattern.quote("beir-v1.0.0-climate-fever.multifield"),
        Pattern.quote("beir-v1.0.0-scifact.multifield")
    ));
    ORDERING.put("Mr.TyDi (v1.1): BM25 regressions", List.of(
        Pattern.quote("mrtydi-v1.1-ar"),
        Pattern.quote("mrtydi-v1.1-bn"),
        Pattern.quote("mrtydi-v1.1-en"),
        Pattern.quote("mrtydi-v1.1-fi"),
        Pattern.quote("mrtydi-v1.1-id"),
        Pattern.quote("mrtydi-v1.1-ja"),
        Pattern.quote("mrtydi-v1.1-ko"),
        Pattern.quote("mrtydi-v1.1-ru"),
        Pattern.quote("mrtydi-v1.1-sw"),
        Pattern.quote("mrtydi-v1.1-te"),
        Pattern.quote("mrtydi-v1.1-th"),
        Pattern.quote("mrtydi-v1.1-ar-aca"),
        Pattern.quote("mrtydi-v1.1-bn-aca"),
        Pattern.quote("mrtydi-v1.1-en-aca"),
        Pattern.quote("mrtydi-v1.1-fi-aca"),
        Pattern.quote("mrtydi-v1.1-id-aca"),
        Pattern.quote("mrtydi-v1.1-ja-aca"),
        Pattern.quote("mrtydi-v1.1-ko-aca"),
        Pattern.quote("mrtydi-v1.1-ru-aca"),
        Pattern.quote("mrtydi-v1.1-sw-aca"),
        Pattern.quote("mrtydi-v1.1-te-aca"),
        Pattern.quote("mrtydi-v1.1-th-aca")
    ));
    ORDERING.put("MIRACL (v1.0): BM25 regressions", List.of(
        Pattern.quote("miracl-v1.0-ar"),
        Pattern.quote("miracl-v1.0-bn"),
        Pattern.quote("miracl-v1.0-en"),
        Pattern.quote("miracl-v1.0-es"),
        Pattern.quote("miracl-v1.0-fa"),
        Pattern.quote("miracl-v1.0-fi"),
        Pattern.quote("miracl-v1.0-fr"),
        Pattern.quote("miracl-v1.0-hi"),
        Pattern.quote("miracl-v1.0-id"),
        Pattern.quote("miracl-v1.0-ja"),
        Pattern.quote("miracl-v1.0-ko"),
        Pattern.quote("miracl-v1.0-ru"),
        Pattern.quote("miracl-v1.0-sw"),
        Pattern.quote("miracl-v1.0-te"),
        Pattern.quote("miracl-v1.0-th"),
        Pattern.quote("miracl-v1.0-zh"),
        Pattern.quote("miracl-v1.0-ar-aca"),
        Pattern.quote("miracl-v1.0-bn-aca"),
        Pattern.quote("miracl-v1.0-en-aca"),
        Pattern.quote("miracl-v1.0-es-aca"),
        Pattern.quote("miracl-v1.0-fa-aca"),
        Pattern.quote("miracl-v1.0-fi-aca"),
        Pattern.quote("miracl-v1.0-fr-aca"),
        Pattern.quote("miracl-v1.0-hi-aca"),
        Pattern.quote("miracl-v1.0-id-aca"),
        Pattern.quote("miracl-v1.0-ja-aca"),
        Pattern.quote("miracl-v1.0-ko-aca"),
        Pattern.quote("miracl-v1.0-ru-aca"),
        Pattern.quote("miracl-v1.0-sw-aca"),
        Pattern.quote("miracl-v1.0-te-aca"),
        Pattern.quote("miracl-v1.0-th-aca"),
        Pattern.quote("miracl-v1.0-zh-aca")
    ));
    ORDERING.put("Other cross-lingual and multi-lingual regressions", List.of(
        Pattern.quote("ntcir8-zh"),
        Pattern.quote("clef06-fr"),
        Pattern.quote("trec02-ar"),
        Pattern.quote("fire12-bn"),
        Pattern.quote("fire12-hi"),
        Pattern.quote("fire12-en"),
        Pattern.quote("hc4-v1.0-fa"),
        Pattern.quote("hc4-v1.0-ru"),
        Pattern.quote("hc4-v1.0-zh"),
        Pattern.quote("hc4-neuclir22-fa"),
        Pattern.quote("hc4-neuclir22-ru"),
        Pattern.quote("hc4-neuclir22-zh"),
        Pattern.quote("hc4-neuclir22-fa-en"),
        Pattern.quote("hc4-neuclir22-ru-en"),
        Pattern.quote("hc4-neuclir22-zh-en"),
        Pattern.quote("neuclir22-fa-qt"),
        Pattern.quote("neuclir22-fa-dt"),
        Pattern.quote("neuclir22-ru-qt"),
        Pattern.quote("neuclir22-ru-dt"),
        Pattern.quote("neuclir22-zh-qt"),
        Pattern.quote("neuclir22-zh-dt"),
        Pattern.quote("neuclir22-fa-qt-splade"),
        Pattern.quote("neuclir22-fa-dt-splade"),
        Pattern.quote("neuclir22-ru-qt-splade"),
        Pattern.quote("neuclir22-ru-dt-splade"),
        Pattern.quote("neuclir22-zh-qt-splade"),
        Pattern.quote("neuclir22-zh-dt-splade"),
        Pattern.quote("ciral-v1.0-ha"),
        Pattern.quote("ciral-v1.0-so"),
        Pattern.quote("ciral-v1.0-sw"),
        Pattern.quote("ciral-v1.0-yo"),
        Pattern.quote("ciral-v1.0-ha-en"),
        Pattern.quote("ciral-v1.0-so-en"),
        Pattern.quote("ciral-v1.0-sw-en"),
        Pattern.quote("ciral-v1.0-yo-en")
    ));
    ORDERING.put("BRIGHT: BM25", List.of(
        Pattern.quote("bright-aops"),
        Pattern.quote("bright-biology"),
        Pattern.quote("bright-earth-science"),
        Pattern.quote("bright-economics"),
        Pattern.quote("bright-leetcode"),
        Pattern.quote("bright-pony"),
        Pattern.quote("bright-psychology"),
        Pattern.quote("bright-robotics"),
        Pattern.quote("bright-stackoverflow"),
        Pattern.quote("bright-sustainable-living"),
        Pattern.quote("bright-theoremqa-questions"),
        Pattern.quote("bright-theoremqa-theorems"),
        Pattern.quote("bright-aops.bm25qs"),
        Pattern.quote("bright-biology.bm25qs"),
        Pattern.quote("bright-earth-science.bm25qs"),
        Pattern.quote("bright-economics.bm25qs"),
        Pattern.quote("bright-leetcode.bm25qs"),
        Pattern.quote("bright-pony.bm25qs"),
        Pattern.quote("bright-psychology.bm25qs"),
        Pattern.quote("bright-robotics.bm25qs"),
        Pattern.quote("bright-stackoverflow.bm25qs"),
        Pattern.quote("bright-sustainable-living.bm25qs"),
        Pattern.quote("bright-theoremqa-questions.bm25qs"),
        Pattern.quote("bright-theoremqa-theorems.bm25qs")
    ));
    ORDERING.put("BRIGHT: SPLADE-v3", List.of(
        Pattern.quote("bright-aops.splade-v3.onnx"),
        Pattern.quote("bright-biology.splade-v3.onnx"),
        Pattern.quote("bright-earth-science.splade-v3.onnx"),
        Pattern.quote("bright-economics.splade-v3.onnx"),
        Pattern.quote("bright-leetcode.splade-v3.onnx"),
        Pattern.quote("bright-pony.splade-v3.onnx"),
        Pattern.quote("bright-psychology.splade-v3.onnx"),
        Pattern.quote("bright-robotics.splade-v3.onnx"),
        Pattern.quote("bright-stackoverflow.splade-v3.onnx"),
        Pattern.quote("bright-sustainable-living.splade-v3.onnx"),
        Pattern.quote("bright-theoremqa-questions.splade-v3.onnx"),
        Pattern.quote("bright-theoremqa-theorems.splade-v3.onnx"),
        Pattern.quote("bright-aops.splade-v3.cached"),
        Pattern.quote("bright-biology.splade-v3.cached"),
        Pattern.quote("bright-earth-science.splade-v3.cached"),
        Pattern.quote("bright-economics.splade-v3.cached"),
        Pattern.quote("bright-leetcode.splade-v3.cached"),
        Pattern.quote("bright-pony.splade-v3.cached"),
        Pattern.quote("bright-psychology.splade-v3.cached"),
        Pattern.quote("bright-robotics.splade-v3.cached"),
        Pattern.quote("bright-stackoverflow.splade-v3.cached"),
        Pattern.quote("bright-sustainable-living.splade-v3.cached"),
        Pattern.quote("bright-theoremqa-questions.splade-v3.cached"),
        Pattern.quote("bright-theoremqa-theorems.splade-v3.cached")
    ));
    ORDERING.put("BRIGHT: BGE-large-en-v1.5", List.of(
        Pattern.quote("bright-aops.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-biology.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-earth-science.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-economics.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-leetcode.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-pony.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-psychology.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-robotics.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-stackoverflow.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-sustainable-living.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-theoremqa-questions.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-theoremqa-theorems.bge-large-en-v1.5.flat.onnx"),
        Pattern.quote("bright-aops.bge-large-en-v1.5.flat.cached"),
        Pattern.quote("bright-biology.bge-large-en-v1.5.flat.cached"),
        Pattern.quote("bright-earth-science.bge-large-en-v1.5.flat.cached"),
        Pattern.quote("bright-economics.bge-large-en-v1.5.flat.cached"),
        Pattern.quote("bright-leetcode.bge-large-en-v1.5.flat.cached"),
        Pattern.quote("bright-pony.bge-large-en-v1.5.flat.cached"),
        Pattern.quote("bright-psychology.bge-large-en-v1.5.flat.cached"),
        Pattern.quote("bright-robotics.bge-large-en-v1.5.flat.cached"),
        Pattern.quote("bright-stackoverflow.bge-large-en-v1.5.flat.cached"),
        Pattern.quote("bright-sustainable-living.bge-large-en-v1.5.flat.cached"),
        Pattern.quote("bright-theoremqa-questions.bge-large-en-v1.5.flat.cached"),
        Pattern.quote("bright-theoremqa-theorems.bge-large-en-v1.5.flat.cached")
    ));
    ORDERING.put("Other regressions", List.of(
        Pattern.quote("backgroundlinking18"),
        Pattern.quote("backgroundlinking19"),
        Pattern.quote("backgroundlinking20"),
        Pattern.quote("disk12"),
        Pattern.quote("disk45"),
        Pattern.quote("robust05"),
        Pattern.quote("core17"),
        Pattern.quote("core18"),
        Pattern.quote("mb11"),
        Pattern.quote("mb13"),
        Pattern.quote("car17v1.5"),
        Pattern.quote("car17v2.0"),
        Pattern.quote("car17v2.0-doc2query"),
        Pattern.quote("wt10g"),
        Pattern.quote("gov2"),
        Pattern.quote("cw09b"),
        Pattern.quote("cw12b13"),
        Pattern.quote("cw12"),
        Pattern.quote("fever"),
        Pattern.quote("wikipedia-dpr-100w-bm25"),
        Pattern.quote("wiki-all-6-3-tamber-bm25"),
        Pattern.quote("disk45")
    ));
  }

  @Test
  public void generateDocs() throws Exception {
    ObjectMapper mapper = new ObjectMapper(new YAMLFactory());
    URL templatesRoot = GenerateReproductionDocsFromDocumentCollectionTest.class.getResource("/reproduce/from-document-collection/docgen");

    assert templatesRoot != null;
    for (final File fileEntry : Objects.requireNonNull(new File(templatesRoot.toURI()).listFiles())) {
      // This is the name of the test, which can be different from the name of the collection,
      // e.g., multiple topics run on the same collection.
      String testName = fileEntry.getName().replaceAll(".template", "");

      URL yaml = GenerateReproductionDocsFromDocumentCollectionTest.class.getResource(String.format("/reproduce/from-document-collection/configs/%s.yaml", testName));
      DataModel data = mapper.readValue(new File(yaml.toURI()), DataModel.class);
      String corpus = data.getCorpus();
      String download_corpus = data.getDownload_corpus();

      Map<String, String> valuesMap = new HashMap<>();
      valuesMap.put("root_path", "../../..");
      valuesMap.put("yaml", String.format("../../../src/main/resources/reproduce/from-document-collection/configs/%s.yaml", testName));
      valuesMap.put("template", String.format("../../../src/main/resources/reproduce/from-document-collection/docgen/%s.template", testName));
      valuesMap.put("test_name", testName);
      valuesMap.put("corpus", corpus);
      valuesMap.put("download_url", data.getDownload_url());
      valuesMap.put("download_checksum", data.getDownload_checksum());
      valuesMap.put("download_corpus", download_corpus);
      valuesMap.put("index_cmds", data.generateIndexingCommand(corpus));
      valuesMap.put("ranking_cmds", data.generateRankingCommand(corpus));
      valuesMap.put("converting_cmds", data.generateConvertingCommand(corpus));
      valuesMap.put("eval_cmds", data.generateEvalCommand(corpus));
      valuesMap.put("effectiveness", data.generateEffectiveness(corpus));

      StringSubstitutor sub = new StringSubstitutor(valuesMap);
      URL template = GenerateReproductionDocsFromDocumentCollectionTest.class.getResource(String.format("/reproduce/from-document-collection/docgen/%s.template", testName));
      assertNotNull(template);

      Scanner scanner = new Scanner(new File(template.toURI()), StandardCharsets.UTF_8);
      String text = scanner.useDelimiter("\\A").next();
      scanner.close();
      String resolvedString = sub.replace(text);

      FileUtils.writeStringToFile(new File(String.format("docs/reproduce/from-document-collection/%s.md", testName)),
        resolvedString, "UTF-8");
    }
  }

  @Test
  public void generateOverviewDoc() throws Exception {
    Path configsPath = Path.of("src/main/resources/reproduce/from-document-collection/configs");
    List<String> configs = Files.list(configsPath)
        .filter(path -> path.getFileName().toString().endsWith(".yaml"))
        .map(path -> path.getFileName().toString().replaceAll("\\.yaml$", ""))
        .sorted()
        .toList();

    StringBuilder invocations = new StringBuilder();
    Set<String> emitted = new LinkedHashSet<>();

    for (Map.Entry<String, List<String>> entry : ORDERING.entrySet()) {
      List<String> groupConfigs = new ArrayList<>();
      for (String regex : entry.getValue()) {
        if (regex.equals(Pattern.quote(""))) {
          groupConfigs.add(" ");
          continue;
        }

        Pattern pattern = Pattern.compile(regex);
        for (String config : configs) {
          if (!emitted.contains(config) && pattern.matcher(config).matches()) {
            groupConfigs.add(config);
            emitted.add(config);
          }
        }
      }

      if (groupConfigs.isEmpty()) {
        continue;
      }

      invocations.append("<details>\n");
      invocations.append("<summary>").append(entry.getKey()).append("</summary>\n\n");
      invocations.append("```bash\n");
      for (String config : groupConfigs) {
        if (config.equals(" ")) {
          invocations.append("\n");
          continue;
        }

        invocations.append("bin/run.sh io.anserini.reproduce.ReproduceFromDocumentCollection")
            .append(" --index --verify --search --config ").append(config)
            .append(" > logs/log.").append(config).append(".txt 2>&1 &\n");
      }
      invocations.append("```\n\n</details>\n");
    }

    Map<String, String> valuesMap = new HashMap<>();
    valuesMap.put("invocations", invocations.toString().trim());

    StringSubstitutor sub = new StringSubstitutor(valuesMap);
    String text = Files.readString(Path.of("docs/reproduce-from-document-collection.template"), StandardCharsets.UTF_8);
    String resolvedString = sub.replace(text);

    FileUtils.writeStringToFile(new File("docs/reproduce-from-document-collection.md"), resolvedString, "UTF-8");
  }


}
