---
corpus: cw09b
corpus_path: collections/web/ClueWeb09b/

index_path: indexes/lucene-index.cw09b/
collection_class: ClueWeb09Collection
generator_class: DefaultLuceneDocumentGenerator
index_threads: 44
index_options: -storeRaw
index_stats:
  documents: 50219783
  documents (non-empty): 50219665
  total terms: 31345664606

metrics:
  - metric: MAP
    command: bin/trec_eval
    params: -m map
    separator: "\t"
    parse_index: 2
    metric_precision: 4
    can_combine: true
  - metric: P30
    command: bin/trec_eval
    params: -m P.30
    separator: "\t"
    parse_index: 2
    metric_precision: 4
    can_combine: true
  - metric: nDCG@20
    command: tools/eval/gdeval.pl
    separator: ","
    parse_index: 2
    metric_precision: 4
  - metric: ERR@20
    command: tools/eval/gdeval.pl
    separator: ","
    parse_index: 3
    metric_precision: 4

topic_reader: Webxml
topics:
  - name: "[TREC 2010 Web Track (Topics 51-100)](https://github.com/castorini/anserini-tools/tree/master/topics-and-qrels/topics.web.51-100.txt)"
    id: trec2010
    path: topics.web.51-100.txt
    qrel: qrels.web.51-100.txt
  - name: "[TREC 2011 Web Track (Topics 101-150)](https://github.com/castorini/anserini-tools/tree/master/topics-and-qrels/topics.web.101-150.txt)"
    id: trec2011
    path: topics.web.101-150.txt
    qrel: qrels.web.101-150.txt
  - name: "[TREC 2012 Web Track (Topics 151-200)](https://github.com/castorini/anserini-tools/tree/master/topics-and-qrels/topics.web.151-200.txt)"
    id: trec2012
    path: topics.web.151-200.txt
    qrel: qrels.web.151-200.txt

models:
  - name: bm25
    display: BM25
    params: -parallelism 16 -bm25
    results:
      MAP:
        - 0.1126
        - 0.1096
        - 0.1103
      P30:
        - 0.2660
        - 0.2513
        - 0.2153
      nDCG@20:
        - 0.1365
        - 0.1895
        - 0.1016
      ERR@20:
        - 0.0733
        - 0.0960
        - 0.1324
  - name: bm25+rm3
    display: +RM3
    params: -parallelism 16 -bm25 -rm3 -collection ClueWeb09Collection
    results:
      MAP:
        - 0.0932
        - 0.1081
        - 0.1110
      P30:
        - 0.2375
        - 0.2447
        - 0.1967
      nDCG@20:
        - 0.1403
        - 0.1935
        - 0.0923
      ERR@20:
        - 0.0773
        - 0.0976
        - 0.1508
  - name: bm25+ax
    display: +Ax
    params: -parallelism 16 -bm25 -axiom -axiom.beta 0.1 -rerankCutoff 20 -collection ClueWeb09Collection
    results:
      MAP:
        - 0.0953
        - 0.0942
        - 0.1346
      P30:
        - 0.2465
        - 0.2220
        - 0.2527
      nDCG@20:
        - 0.1735
        - 0.1657
        - 0.1403
      ERR@20:
        - 0.1015
        - 0.1041
        - 0.2393
  - name: ql
    display: QL
    params: -parallelism 16 -qld
    results:
      MAP:
        - 0.1056
        - 0.0960
        - 0.1069
      P30:
        - 0.2424
        - 0.2153
        - 0.2067
      nDCG@20:
        - 0.1137
        - 0.1631
        - 0.0880
      ERR@20:
        - 0.0597
        - 0.0850
        - 0.1337
  - name: ql+rm3
    display: +RM3
    params: -parallelism 16 -qld -rm3 -collection ClueWeb09Collection
    results:
      MAP:
        - 0.1021
        - 0.0835
        - 0.1055
      P30:
        - 0.2299
        - 0.2060
        - 0.2007
      nDCG@20:
        - 0.1186
        - 0.1432
        - 0.0896
      ERR@20:
        - 0.0591
        - 0.0779
        - 0.1330
  - name: ql+ax
    display: +Ax
    params: -parallelism 16 -qld -axiom -axiom.beta 0.1 -rerankCutoff 20 -collection ClueWeb09Collection
    results:
      MAP:
        - 0.1084
        - 0.0856
        - 0.1246
      P30:
        - 0.2611
        - 0.2127
        - 0.2287
      nDCG@20:
        - 0.1453
        - 0.1521
        - 0.1075
      ERR@20:
        - 0.0707
        - 0.0809
        - 0.1537
