---
corpus: wt10g
corpus_path: collections/web/wt10g/

index_path: indexes/lucene-index.wt10g/
collection_class: TrecwebCollection
generator_class: DefaultLuceneDocumentGenerator
index_threads: 16
index_options: -storePositions -storeDocvectors -storeRaw
index_stats:
  documents: 1688001
  documents (non-empty): 1687898
  total terms: 746443752

metrics:
  - metric: MAP
    command: bin/trec_eval
    params: -m map
    separator: "\t"
    parse_index: 2
    metric_precision: 4
    can_combine: true
  - metric: P30
    command: bin/trec_eval
    params: -m P.30
    separator: "\t"
    parse_index: 2
    metric_precision: 4
    can_combine: true

topic_reader: Trec
topics:
  - name: "[Wt10g (Topics 451-550)](https://github.com/castorini/anserini-tools/tree/master/topics-and-qrels/topics.adhoc.451-550.txt)"
    id: wt10g
    path: topics.adhoc.451-550.txt
    qrel: qrels.adhoc.451-550.txt

models:
  - name: bm25
    display: BM25
    params: -bm25
    results:
      MAP:
        - 0.1952
      P30:
        - 0.2214
  - name: bm25+rm3
    display: +RM3
    params: -bm25 -rm3
    results:
      MAP:
        - 0.2219
      P30:
        - 0.2381
  - name: bm25+ax
    display: +Ax
    params: -bm25 -axiom -axiom.beta 0.1 -rerankCutoff 20
    results:
      MAP:
        - 0.2187
      P30:
        - 0.2439
  - name: ql
    display: QL
    params: -qld
    results:
      MAP:
        - 0.1977
      P30:
        - 0.2177
  - name: ql+rm3
    display: +RM3
    params: -qld -rm3
    results:
      MAP:
        - 0.2149
      P30:
        - 0.2316
  - name: ql+ax
    display: +Ax
    params: -qld -axiom -axiom.beta 0.1 -rerankCutoff 20
    results:
      MAP:
        - 0.2231
      P30:
        - 0.2497
