---
corpus: msmarco-passage-openai-ada2.parquet
corpus_path: collections/msmarco/msmarco-passage-openai-ada2.parquet/

download_url: https://rgw.cs.uwaterloo.ca/pyserini/data/msmarco-passage-openai-ada2.parquet.tar
download_checksum: a8fddf594c9b8e771637968033b12f6d

index_path: indexes/lucene-flat.msmarco-v1-passage.openai-ada2/
index_type: flat
collection_class: ParquetDenseVectorCollection
generator_class: DenseVectorDocumentGenerator
index_threads: 16
index_options: ""

metrics:
  - metric: AP@1000
    command: bin/trec_eval
    params: -c -m map
    separator: "\t"
    parse_index: 2
    metric_precision: 4
    can_combine: false
  - metric: RR@10
    command: bin/trec_eval
    params: -c -M 10 -m recip_rank
    separator: "\t"
    parse_index: 2
    metric_precision: 4
    can_combine: false
  - metric: R@100
    command: bin/trec_eval
    params: -c -m recall.100
    separator: "\t"
    parse_index: 2
    metric_precision: 4
    can_combine: false
  - metric: R@1000
    command: bin/trec_eval
    params: -c -m recall.1000
    separator: "\t"
    parse_index: 2
    metric_precision: 4
    can_combine: false

topic_reader: JsonIntVector
topics:
  - name: "[MS MARCO Passage: Dev](https://github.com/microsoft/MSMARCO-Passage-Ranking)"
    id: dev
    path: topics.msmarco-passage.dev-subset.openai-ada2.jsonl.gz
    qrel: qrels.msmarco-passage.dev-subset.txt

models:
  - name: openai-ada2-flat-cached
    display: OpenAI-ada2
    type: flat
    params: -hits 1000 -threads 16
    results:
      AP@1000:
        - 0.3505
      RR@10:
        - 0.3434
      R@100:
        - 0.8996
      R@1000:
        - 0.9858
