conditions:
  - name: bge-base-en-v1.5.flat.cached
    display: "bge-base-en-v1.5 w/ flat indexes (cached queries)"
    command: io.anserini.search.SearchFlatDenseVectors -threads $threads -index beir-v1.0.0-$topics.bge-base-en-v1.5.flat -topics beir-$topics.bge-base-en-v1.5 -output $output -removeQuery
    topics:
      - topic_key: trec-covid
        eval_key: beir-v1.0.0-trec-covid.test
        expected_scores:
          nDCG@10: 0.7815
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: bioasq
        eval_key: beir-v1.0.0-bioasq.test
        expected_scores:
          nDCG@10: 0.4148
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: nfcorpus
        eval_key: beir-v1.0.0-nfcorpus.test
        expected_scores:
          nDCG@10: 0.3738
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: nq
        eval_key: beir-v1.0.0-nq.test
        expected_scores:
          nDCG@10: 0.5415
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: hotpotqa
        eval_key: beir-v1.0.0-hotpotqa.test
        expected_scores:
          nDCG@10: 0.7259
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: fiqa
        eval_key: beir-v1.0.0-fiqa.test
        expected_scores:
          nDCG@10: 0.4065
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: signal1m
        eval_key: beir-v1.0.0-signal1m.test
        expected_scores:
          nDCG@10: 0.2886
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: trec-news
        eval_key: beir-v1.0.0-trec-news.test
        expected_scores:
          nDCG@10: 0.4424
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: robust04
        eval_key: beir-v1.0.0-robust04.test
        expected_scores:
          nDCG@10: 0.4435
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: arguana
        eval_key: beir-v1.0.0-arguana.test
        expected_scores:
          nDCG@10: 0.6375
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: webis-touche2020
        eval_key: beir-v1.0.0-webis-touche2020.test
        expected_scores:
          nDCG@10: 0.2571
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-android
        eval_key: beir-v1.0.0-cqadupstack-android.test
        expected_scores:
          nDCG@10: 0.5076
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-english
        eval_key: beir-v1.0.0-cqadupstack-english.test
        expected_scores:
          nDCG@10: 0.4857
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-gaming
        eval_key: beir-v1.0.0-cqadupstack-gaming.test
        expected_scores:
          nDCG@10: 0.5967
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-gis
        eval_key: beir-v1.0.0-cqadupstack-gis.test
        expected_scores:
          nDCG@10: 0.4131
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-mathematica
        eval_key: beir-v1.0.0-cqadupstack-mathematica.test
        expected_scores:
          nDCG@10: 0.3163
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-physics
        eval_key: beir-v1.0.0-cqadupstack-physics.test
        expected_scores:
          nDCG@10: 0.4724
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-programmers
        eval_key: beir-v1.0.0-cqadupstack-programmers.test
        expected_scores:
          nDCG@10: 0.4238
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-stats
        eval_key: beir-v1.0.0-cqadupstack-stats.test
        expected_scores:
          nDCG@10: 0.3728
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-tex
        eval_key: beir-v1.0.0-cqadupstack-tex.test
        expected_scores:
          nDCG@10: 0.3115
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-unix
        eval_key: beir-v1.0.0-cqadupstack-unix.test
        expected_scores:
          nDCG@10: 0.4220
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-webmasters
        eval_key: beir-v1.0.0-cqadupstack-webmasters.test
        expected_scores:
          nDCG@10: 0.4072
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: cqadupstack-wordpress
        eval_key: beir-v1.0.0-cqadupstack-wordpress.test
        expected_scores:
          nDCG@10: 0.3547
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: quora
        eval_key: beir-v1.0.0-quora.test
        expected_scores:
          nDCG@10: 0.8876
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: dbpedia-entity
        eval_key: beir-v1.0.0-dbpedia-entity.test
        expected_scores:
          nDCG@10: 0.4073
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: scidocs
        eval_key: beir-v1.0.0-scidocs.test
        expected_scores:
          nDCG@10: 0.2172
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: fever
        eval_key: beir-v1.0.0-fever.test
        expected_scores:
          nDCG@10: 0.8629
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: climate-fever
        eval_key: beir-v1.0.0-climate-fever.test
        expected_scores:
          nDCG@10: 0.3117
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
      - topic_key: scifact
        eval_key: beir-v1.0.0-scifact.test
        expected_scores:
          nDCG@10: 0.7408
        metric_definitions:
          nDCG@10: "-c -m ndcg_cut.10"
