// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/CommonIndexFormat.proto

package io.anserini.cidxf;

public final class CommonIndexFormat {
  private CommonIndexFormat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PostingOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.anserini.cidxf.Posting)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 docid = 1;</code>
     */
    int getDocid();

    /**
     * <code>int32 tf = 2;</code>
     */
    int getTf();
  }
  /**
   * Protobuf type {@code io.anserini.cidxf.Posting}
   */
  public  static final class Posting extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.anserini.cidxf.Posting)
      PostingOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Posting.newBuilder() to construct.
    private Posting(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Posting() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Posting();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Posting(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              docid_ = input.readInt32();
              break;
            }
            case 16: {

              tf_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.anserini.cidxf.CommonIndexFormat.internal_static_io_anserini_cidxf_Posting_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.anserini.cidxf.CommonIndexFormat.internal_static_io_anserini_cidxf_Posting_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.anserini.cidxf.CommonIndexFormat.Posting.class, io.anserini.cidxf.CommonIndexFormat.Posting.Builder.class);
    }

    public static final int DOCID_FIELD_NUMBER = 1;
    private int docid_;
    /**
     * <code>int32 docid = 1;</code>
     */
    public int getDocid() {
      return docid_;
    }

    public static final int TF_FIELD_NUMBER = 2;
    private int tf_;
    /**
     * <code>int32 tf = 2;</code>
     */
    public int getTf() {
      return tf_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (docid_ != 0) {
        output.writeInt32(1, docid_);
      }
      if (tf_ != 0) {
        output.writeInt32(2, tf_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (docid_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, docid_);
      }
      if (tf_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, tf_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.anserini.cidxf.CommonIndexFormat.Posting)) {
        return super.equals(obj);
      }
      io.anserini.cidxf.CommonIndexFormat.Posting other = (io.anserini.cidxf.CommonIndexFormat.Posting) obj;

      if (getDocid()
          != other.getDocid()) return false;
      if (getTf()
          != other.getTf()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DOCID_FIELD_NUMBER;
      hash = (53 * hash) + getDocid();
      hash = (37 * hash) + TF_FIELD_NUMBER;
      hash = (53 * hash) + getTf();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.anserini.cidxf.CommonIndexFormat.Posting parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.anserini.cidxf.CommonIndexFormat.Posting parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.anserini.cidxf.CommonIndexFormat.Posting parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.anserini.cidxf.CommonIndexFormat.Posting parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.anserini.cidxf.CommonIndexFormat.Posting parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.anserini.cidxf.CommonIndexFormat.Posting parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.anserini.cidxf.CommonIndexFormat.Posting parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.anserini.cidxf.CommonIndexFormat.Posting parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.anserini.cidxf.CommonIndexFormat.Posting parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.anserini.cidxf.CommonIndexFormat.Posting parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.anserini.cidxf.CommonIndexFormat.Posting parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.anserini.cidxf.CommonIndexFormat.Posting parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.anserini.cidxf.CommonIndexFormat.Posting prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.anserini.cidxf.Posting}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.anserini.cidxf.Posting)
        io.anserini.cidxf.CommonIndexFormat.PostingOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.anserini.cidxf.CommonIndexFormat.internal_static_io_anserini_cidxf_Posting_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.anserini.cidxf.CommonIndexFormat.internal_static_io_anserini_cidxf_Posting_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.anserini.cidxf.CommonIndexFormat.Posting.class, io.anserini.cidxf.CommonIndexFormat.Posting.Builder.class);
      }

      // Construct using io.anserini.cidxf.CommonIndexFormat.Posting.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        docid_ = 0;

        tf_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.anserini.cidxf.CommonIndexFormat.internal_static_io_anserini_cidxf_Posting_descriptor;
      }

      @java.lang.Override
      public io.anserini.cidxf.CommonIndexFormat.Posting getDefaultInstanceForType() {
        return io.anserini.cidxf.CommonIndexFormat.Posting.getDefaultInstance();
      }

      @java.lang.Override
      public io.anserini.cidxf.CommonIndexFormat.Posting build() {
        io.anserini.cidxf.CommonIndexFormat.Posting result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.anserini.cidxf.CommonIndexFormat.Posting buildPartial() {
        io.anserini.cidxf.CommonIndexFormat.Posting result = new io.anserini.cidxf.CommonIndexFormat.Posting(this);
        result.docid_ = docid_;
        result.tf_ = tf_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.anserini.cidxf.CommonIndexFormat.Posting) {
          return mergeFrom((io.anserini.cidxf.CommonIndexFormat.Posting)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.anserini.cidxf.CommonIndexFormat.Posting other) {
        if (other == io.anserini.cidxf.CommonIndexFormat.Posting.getDefaultInstance()) return this;
        if (other.getDocid() != 0) {
          setDocid(other.getDocid());
        }
        if (other.getTf() != 0) {
          setTf(other.getTf());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.anserini.cidxf.CommonIndexFormat.Posting parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.anserini.cidxf.CommonIndexFormat.Posting) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int docid_ ;
      /**
       * <code>int32 docid = 1;</code>
       */
      public int getDocid() {
        return docid_;
      }
      /**
       * <code>int32 docid = 1;</code>
       */
      public Builder setDocid(int value) {
        
        docid_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 docid = 1;</code>
       */
      public Builder clearDocid() {
        
        docid_ = 0;
        onChanged();
        return this;
      }

      private int tf_ ;
      /**
       * <code>int32 tf = 2;</code>
       */
      public int getTf() {
        return tf_;
      }
      /**
       * <code>int32 tf = 2;</code>
       */
      public Builder setTf(int value) {
        
        tf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 tf = 2;</code>
       */
      public Builder clearTf() {
        
        tf_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.anserini.cidxf.Posting)
    }

    // @@protoc_insertion_point(class_scope:io.anserini.cidxf.Posting)
    private static final io.anserini.cidxf.CommonIndexFormat.Posting DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.anserini.cidxf.CommonIndexFormat.Posting();
    }

    public static io.anserini.cidxf.CommonIndexFormat.Posting getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Posting>
        PARSER = new com.google.protobuf.AbstractParser<Posting>() {
      @java.lang.Override
      public Posting parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Posting(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Posting> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Posting> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.anserini.cidxf.CommonIndexFormat.Posting getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface PostingsListOrBuilder extends
      // @@protoc_insertion_point(interface_extends:io.anserini.cidxf.PostingsList)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string term = 1;</code>
     */
    java.lang.String getTerm();
    /**
     * <code>string term = 1;</code>
     */
    com.google.protobuf.ByteString
        getTermBytes();

    /**
     * <code>int64 df = 2;</code>
     */
    long getDf();

    /**
     * <code>int64 cf = 3;</code>
     */
    long getCf();

    /**
     * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
     */
    java.util.List<io.anserini.cidxf.CommonIndexFormat.Posting> 
        getPostingList();
    /**
     * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
     */
    io.anserini.cidxf.CommonIndexFormat.Posting getPosting(int index);
    /**
     * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
     */
    int getPostingCount();
    /**
     * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
     */
    java.util.List<? extends io.anserini.cidxf.CommonIndexFormat.PostingOrBuilder> 
        getPostingOrBuilderList();
    /**
     * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
     */
    io.anserini.cidxf.CommonIndexFormat.PostingOrBuilder getPostingOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code io.anserini.cidxf.PostingsList}
   */
  public  static final class PostingsList extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:io.anserini.cidxf.PostingsList)
      PostingsListOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PostingsList.newBuilder() to construct.
    private PostingsList(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PostingsList() {
      term_ = "";
      posting_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PostingsList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PostingsList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              term_ = s;
              break;
            }
            case 16: {

              df_ = input.readInt64();
              break;
            }
            case 24: {

              cf_ = input.readInt64();
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000001) != 0)) {
                posting_ = new java.util.ArrayList<io.anserini.cidxf.CommonIndexFormat.Posting>();
                mutable_bitField0_ |= 0x00000001;
              }
              posting_.add(
                  input.readMessage(io.anserini.cidxf.CommonIndexFormat.Posting.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) != 0)) {
          posting_ = java.util.Collections.unmodifiableList(posting_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return io.anserini.cidxf.CommonIndexFormat.internal_static_io_anserini_cidxf_PostingsList_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return io.anserini.cidxf.CommonIndexFormat.internal_static_io_anserini_cidxf_PostingsList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              io.anserini.cidxf.CommonIndexFormat.PostingsList.class, io.anserini.cidxf.CommonIndexFormat.PostingsList.Builder.class);
    }

    public static final int TERM_FIELD_NUMBER = 1;
    private volatile java.lang.Object term_;
    /**
     * <code>string term = 1;</code>
     */
    public java.lang.String getTerm() {
      java.lang.Object ref = term_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        term_ = s;
        return s;
      }
    }
    /**
     * <code>string term = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTermBytes() {
      java.lang.Object ref = term_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        term_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DF_FIELD_NUMBER = 2;
    private long df_;
    /**
     * <code>int64 df = 2;</code>
     */
    public long getDf() {
      return df_;
    }

    public static final int CF_FIELD_NUMBER = 3;
    private long cf_;
    /**
     * <code>int64 cf = 3;</code>
     */
    public long getCf() {
      return cf_;
    }

    public static final int POSTING_FIELD_NUMBER = 4;
    private java.util.List<io.anserini.cidxf.CommonIndexFormat.Posting> posting_;
    /**
     * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
     */
    public java.util.List<io.anserini.cidxf.CommonIndexFormat.Posting> getPostingList() {
      return posting_;
    }
    /**
     * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
     */
    public java.util.List<? extends io.anserini.cidxf.CommonIndexFormat.PostingOrBuilder> 
        getPostingOrBuilderList() {
      return posting_;
    }
    /**
     * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
     */
    public int getPostingCount() {
      return posting_.size();
    }
    /**
     * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
     */
    public io.anserini.cidxf.CommonIndexFormat.Posting getPosting(int index) {
      return posting_.get(index);
    }
    /**
     * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
     */
    public io.anserini.cidxf.CommonIndexFormat.PostingOrBuilder getPostingOrBuilder(
        int index) {
      return posting_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getTermBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, term_);
      }
      if (df_ != 0L) {
        output.writeInt64(2, df_);
      }
      if (cf_ != 0L) {
        output.writeInt64(3, cf_);
      }
      for (int i = 0; i < posting_.size(); i++) {
        output.writeMessage(4, posting_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getTermBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, term_);
      }
      if (df_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, df_);
      }
      if (cf_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(3, cf_);
      }
      for (int i = 0; i < posting_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, posting_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof io.anserini.cidxf.CommonIndexFormat.PostingsList)) {
        return super.equals(obj);
      }
      io.anserini.cidxf.CommonIndexFormat.PostingsList other = (io.anserini.cidxf.CommonIndexFormat.PostingsList) obj;

      if (!getTerm()
          .equals(other.getTerm())) return false;
      if (getDf()
          != other.getDf()) return false;
      if (getCf()
          != other.getCf()) return false;
      if (!getPostingList()
          .equals(other.getPostingList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TERM_FIELD_NUMBER;
      hash = (53 * hash) + getTerm().hashCode();
      hash = (37 * hash) + DF_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getDf());
      hash = (37 * hash) + CF_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCf());
      if (getPostingCount() > 0) {
        hash = (37 * hash) + POSTING_FIELD_NUMBER;
        hash = (53 * hash) + getPostingList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static io.anserini.cidxf.CommonIndexFormat.PostingsList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(io.anserini.cidxf.CommonIndexFormat.PostingsList prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code io.anserini.cidxf.PostingsList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:io.anserini.cidxf.PostingsList)
        io.anserini.cidxf.CommonIndexFormat.PostingsListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return io.anserini.cidxf.CommonIndexFormat.internal_static_io_anserini_cidxf_PostingsList_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return io.anserini.cidxf.CommonIndexFormat.internal_static_io_anserini_cidxf_PostingsList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                io.anserini.cidxf.CommonIndexFormat.PostingsList.class, io.anserini.cidxf.CommonIndexFormat.PostingsList.Builder.class);
      }

      // Construct using io.anserini.cidxf.CommonIndexFormat.PostingsList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getPostingFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        term_ = "";

        df_ = 0L;

        cf_ = 0L;

        if (postingBuilder_ == null) {
          posting_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          postingBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return io.anserini.cidxf.CommonIndexFormat.internal_static_io_anserini_cidxf_PostingsList_descriptor;
      }

      @java.lang.Override
      public io.anserini.cidxf.CommonIndexFormat.PostingsList getDefaultInstanceForType() {
        return io.anserini.cidxf.CommonIndexFormat.PostingsList.getDefaultInstance();
      }

      @java.lang.Override
      public io.anserini.cidxf.CommonIndexFormat.PostingsList build() {
        io.anserini.cidxf.CommonIndexFormat.PostingsList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public io.anserini.cidxf.CommonIndexFormat.PostingsList buildPartial() {
        io.anserini.cidxf.CommonIndexFormat.PostingsList result = new io.anserini.cidxf.CommonIndexFormat.PostingsList(this);
        int from_bitField0_ = bitField0_;
        result.term_ = term_;
        result.df_ = df_;
        result.cf_ = cf_;
        if (postingBuilder_ == null) {
          if (((bitField0_ & 0x00000001) != 0)) {
            posting_ = java.util.Collections.unmodifiableList(posting_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.posting_ = posting_;
        } else {
          result.posting_ = postingBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof io.anserini.cidxf.CommonIndexFormat.PostingsList) {
          return mergeFrom((io.anserini.cidxf.CommonIndexFormat.PostingsList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(io.anserini.cidxf.CommonIndexFormat.PostingsList other) {
        if (other == io.anserini.cidxf.CommonIndexFormat.PostingsList.getDefaultInstance()) return this;
        if (!other.getTerm().isEmpty()) {
          term_ = other.term_;
          onChanged();
        }
        if (other.getDf() != 0L) {
          setDf(other.getDf());
        }
        if (other.getCf() != 0L) {
          setCf(other.getCf());
        }
        if (postingBuilder_ == null) {
          if (!other.posting_.isEmpty()) {
            if (posting_.isEmpty()) {
              posting_ = other.posting_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensurePostingIsMutable();
              posting_.addAll(other.posting_);
            }
            onChanged();
          }
        } else {
          if (!other.posting_.isEmpty()) {
            if (postingBuilder_.isEmpty()) {
              postingBuilder_.dispose();
              postingBuilder_ = null;
              posting_ = other.posting_;
              bitField0_ = (bitField0_ & ~0x00000001);
              postingBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getPostingFieldBuilder() : null;
            } else {
              postingBuilder_.addAllMessages(other.posting_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        io.anserini.cidxf.CommonIndexFormat.PostingsList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (io.anserini.cidxf.CommonIndexFormat.PostingsList) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object term_ = "";
      /**
       * <code>string term = 1;</code>
       */
      public java.lang.String getTerm() {
        java.lang.Object ref = term_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          term_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string term = 1;</code>
       */
      public com.google.protobuf.ByteString
          getTermBytes() {
        java.lang.Object ref = term_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          term_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string term = 1;</code>
       */
      public Builder setTerm(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        term_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string term = 1;</code>
       */
      public Builder clearTerm() {
        
        term_ = getDefaultInstance().getTerm();
        onChanged();
        return this;
      }
      /**
       * <code>string term = 1;</code>
       */
      public Builder setTermBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        term_ = value;
        onChanged();
        return this;
      }

      private long df_ ;
      /**
       * <code>int64 df = 2;</code>
       */
      public long getDf() {
        return df_;
      }
      /**
       * <code>int64 df = 2;</code>
       */
      public Builder setDf(long value) {
        
        df_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 df = 2;</code>
       */
      public Builder clearDf() {
        
        df_ = 0L;
        onChanged();
        return this;
      }

      private long cf_ ;
      /**
       * <code>int64 cf = 3;</code>
       */
      public long getCf() {
        return cf_;
      }
      /**
       * <code>int64 cf = 3;</code>
       */
      public Builder setCf(long value) {
        
        cf_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int64 cf = 3;</code>
       */
      public Builder clearCf() {
        
        cf_ = 0L;
        onChanged();
        return this;
      }

      private java.util.List<io.anserini.cidxf.CommonIndexFormat.Posting> posting_ =
        java.util.Collections.emptyList();
      private void ensurePostingIsMutable() {
        if (!((bitField0_ & 0x00000001) != 0)) {
          posting_ = new java.util.ArrayList<io.anserini.cidxf.CommonIndexFormat.Posting>(posting_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.anserini.cidxf.CommonIndexFormat.Posting, io.anserini.cidxf.CommonIndexFormat.Posting.Builder, io.anserini.cidxf.CommonIndexFormat.PostingOrBuilder> postingBuilder_;

      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public java.util.List<io.anserini.cidxf.CommonIndexFormat.Posting> getPostingList() {
        if (postingBuilder_ == null) {
          return java.util.Collections.unmodifiableList(posting_);
        } else {
          return postingBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public int getPostingCount() {
        if (postingBuilder_ == null) {
          return posting_.size();
        } else {
          return postingBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public io.anserini.cidxf.CommonIndexFormat.Posting getPosting(int index) {
        if (postingBuilder_ == null) {
          return posting_.get(index);
        } else {
          return postingBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public Builder setPosting(
          int index, io.anserini.cidxf.CommonIndexFormat.Posting value) {
        if (postingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostingIsMutable();
          posting_.set(index, value);
          onChanged();
        } else {
          postingBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public Builder setPosting(
          int index, io.anserini.cidxf.CommonIndexFormat.Posting.Builder builderForValue) {
        if (postingBuilder_ == null) {
          ensurePostingIsMutable();
          posting_.set(index, builderForValue.build());
          onChanged();
        } else {
          postingBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public Builder addPosting(io.anserini.cidxf.CommonIndexFormat.Posting value) {
        if (postingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostingIsMutable();
          posting_.add(value);
          onChanged();
        } else {
          postingBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public Builder addPosting(
          int index, io.anserini.cidxf.CommonIndexFormat.Posting value) {
        if (postingBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePostingIsMutable();
          posting_.add(index, value);
          onChanged();
        } else {
          postingBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public Builder addPosting(
          io.anserini.cidxf.CommonIndexFormat.Posting.Builder builderForValue) {
        if (postingBuilder_ == null) {
          ensurePostingIsMutable();
          posting_.add(builderForValue.build());
          onChanged();
        } else {
          postingBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public Builder addPosting(
          int index, io.anserini.cidxf.CommonIndexFormat.Posting.Builder builderForValue) {
        if (postingBuilder_ == null) {
          ensurePostingIsMutable();
          posting_.add(index, builderForValue.build());
          onChanged();
        } else {
          postingBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public Builder addAllPosting(
          java.lang.Iterable<? extends io.anserini.cidxf.CommonIndexFormat.Posting> values) {
        if (postingBuilder_ == null) {
          ensurePostingIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, posting_);
          onChanged();
        } else {
          postingBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public Builder clearPosting() {
        if (postingBuilder_ == null) {
          posting_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          postingBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public Builder removePosting(int index) {
        if (postingBuilder_ == null) {
          ensurePostingIsMutable();
          posting_.remove(index);
          onChanged();
        } else {
          postingBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public io.anserini.cidxf.CommonIndexFormat.Posting.Builder getPostingBuilder(
          int index) {
        return getPostingFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public io.anserini.cidxf.CommonIndexFormat.PostingOrBuilder getPostingOrBuilder(
          int index) {
        if (postingBuilder_ == null) {
          return posting_.get(index);  } else {
          return postingBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public java.util.List<? extends io.anserini.cidxf.CommonIndexFormat.PostingOrBuilder> 
           getPostingOrBuilderList() {
        if (postingBuilder_ != null) {
          return postingBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(posting_);
        }
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public io.anserini.cidxf.CommonIndexFormat.Posting.Builder addPostingBuilder() {
        return getPostingFieldBuilder().addBuilder(
            io.anserini.cidxf.CommonIndexFormat.Posting.getDefaultInstance());
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public io.anserini.cidxf.CommonIndexFormat.Posting.Builder addPostingBuilder(
          int index) {
        return getPostingFieldBuilder().addBuilder(
            index, io.anserini.cidxf.CommonIndexFormat.Posting.getDefaultInstance());
      }
      /**
       * <code>repeated .io.anserini.cidxf.Posting posting = 4;</code>
       */
      public java.util.List<io.anserini.cidxf.CommonIndexFormat.Posting.Builder> 
           getPostingBuilderList() {
        return getPostingFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          io.anserini.cidxf.CommonIndexFormat.Posting, io.anserini.cidxf.CommonIndexFormat.Posting.Builder, io.anserini.cidxf.CommonIndexFormat.PostingOrBuilder> 
          getPostingFieldBuilder() {
        if (postingBuilder_ == null) {
          postingBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              io.anserini.cidxf.CommonIndexFormat.Posting, io.anserini.cidxf.CommonIndexFormat.Posting.Builder, io.anserini.cidxf.CommonIndexFormat.PostingOrBuilder>(
                  posting_,
                  ((bitField0_ & 0x00000001) != 0),
                  getParentForChildren(),
                  isClean());
          posting_ = null;
        }
        return postingBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:io.anserini.cidxf.PostingsList)
    }

    // @@protoc_insertion_point(class_scope:io.anserini.cidxf.PostingsList)
    private static final io.anserini.cidxf.CommonIndexFormat.PostingsList DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new io.anserini.cidxf.CommonIndexFormat.PostingsList();
    }

    public static io.anserini.cidxf.CommonIndexFormat.PostingsList getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PostingsList>
        PARSER = new com.google.protobuf.AbstractParser<PostingsList>() {
      @java.lang.Override
      public PostingsList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PostingsList(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PostingsList> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PostingsList> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public io.anserini.cidxf.CommonIndexFormat.PostingsList getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_anserini_cidxf_Posting_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_anserini_cidxf_Posting_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_io_anserini_cidxf_PostingsList_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_io_anserini_cidxf_PostingsList_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n)src/main/protobuf/CommonIndexFormat.pr" +
      "oto\022\021io.anserini.cidxf\"$\n\007Posting\022\r\n\005doc" +
      "id\030\001 \001(\005\022\n\n\002tf\030\002 \001(\005\"a\n\014PostingsList\022\014\n\004" +
      "term\030\001 \001(\t\022\n\n\002df\030\002 \001(\003\022\n\n\002cf\030\003 \001(\003\022+\n\007po" +
      "sting\030\004 \003(\0132\032.io.anserini.cidxf.Postingb" +
      "\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_io_anserini_cidxf_Posting_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_io_anserini_cidxf_Posting_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_anserini_cidxf_Posting_descriptor,
        new java.lang.String[] { "Docid", "Tf", });
    internal_static_io_anserini_cidxf_PostingsList_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_io_anserini_cidxf_PostingsList_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_io_anserini_cidxf_PostingsList_descriptor,
        new java.lang.String[] { "Term", "Df", "Cf", "Posting", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
