# Generated by Django 3.0.2 on 2020-02-08 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('country', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PoiType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pType', models.IntegerField(choices=[(0, 'others'), (1, 'restaurant'), (2, 'lounge')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Poi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=100)),
                ('priceLV', models.IntegerField(choices=[(0, 'unknown price level'), (1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], default=0)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('ratingCount', models.IntegerField()),
                ('location', models.ForeignKey(default='unknown', on_delete=django.db.models.deletion.SET_DEFAULT, to='planner.Location')),
                ('placeType', models.ForeignKey(default='other types', on_delete=django.db.models.deletion.SET_DEFAULT, to='planner.PoiType')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('starting_time', models.DateTimeField()),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('venue_name', models.CharField(max_length=80)),
                ('url_link', models.TextField()),
                ('venue_url_link', models.TextField()),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Location')),
            ],
        ),
    ]
