# Generated by Django 3.0.2 on 2020-02-08 02:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poi',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='poitype',
            name='pType',
            field=models.CharField(default='unknown', max_length=80),
        ),
    ]
