# Generated by Django 3.0.2 on 2020-02-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0004_auto_20200207_2142'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='poi',
            options={'ordering': ['rating', 'ratingCount']},
        ),
        migrations.AlterField(
            model_name='poi',
            name='priceLV',
            field=models.IntegerField(choices=[(0, 'unknown price level'), (1, '$'), (2, '$$'), (3, '$$$'), (4, '$$$$')], default=0, verbose_name='price level'),
        ),
    ]
