# Generated by Django 3.0.2 on 2020-02-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0005_auto_20200207_2234'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchReq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50)),
                ('date_from', models.DateField()),
                ('date_to', models.DateField()),
                ('budget_min', models.IntegerField()),
                ('budget_max', models.IntegerField()),
                ('keywords', models.CharField(max_length=20)),
            ],
        ),
    ]
