# Generated by Django 3.0.2 on 2020-02-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0006_searchreq'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchreq',
            old_name='budget_max',
            new_name='max_budget',
        ),
        migrations.RenameField(
            model_name='searchreq',
            old_name='budget_min',
            new_name='min_budget',
        ),
        migrations.AlterField(
            model_name='searchreq',
            name='city',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='searchreq',
            name='keywords',
            field=models.CharField(max_length=100),
        ),
    ]
