# Generated by Django 3.0.3 on 2020-03-07 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0007_auto_20200208_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SearchReq',
        ),
        migrations.AlterField(
            model_name='event',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.Location'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='placeType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planner.PoiType'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='priceLV',
            field=models.IntegerField(default=0, verbose_name='price level'),
        ),
        migrations.AlterField(
            model_name='poi',
            name='rating',
            field=models.DecimalField(decimal_places=1, default=-1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='poi',
            name='ratingCount',
            field=models.IntegerField(default=-1),
        ),
    ]
